# Generated by Django 2.1.2 on 2018-10-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='주소')),
                ('creator', models.TextField(verbose_name='생성자')),
                ('abi', models.TextField(verbose_name='abi')),
            ],
        ),
    ]
